#!/bin/bash
#
# SPDX-License-Identifier: Apache-2.0
#
# Authors:
#	2020	Elvis Yao <ElvisCW.Yao@moxa.com>
#
# Description:
#	For Moxa V-2406C series
#

gpio_request() {
	local gpio=${1}

	if [ ! -e "/sys/class/gpio/gpio${gpio}" ]
	then
		echo "${gpio}" > /sys/class/gpio/export
	fi
}

gpio_set_value() {
	local gpio=${1}
	local value=${2}

	gpio_request "${gpio}"
	case "${value}" in
	0)
		echo "low" > "/sys/class/gpio/gpio${gpio}/direction"
		;;
	1)
		echo "high" > "/sys/class/gpio/gpio${gpio}/direction"
		;;
	esac
}

gp() {
	for gpiochip in /sys/class/gpio/gpiochip*
	do
		if cat "${gpiochip}"/label | grep -q "gpio_it87"
		then
			base=$(cat "${gpiochip}"/base)
			break
		fi
	done

	tens=$(($1 / 10))
	units=$(($1 % 10))
	echo $((base + 8 * (tens - 1) + units))
}

bind_hwm_driver() {
	for filename in /sys/bus/i2c/devices/i2c-*/name; do
		i2c_devname=$(cat ${filename})
		if [[ $i2c_devname == *"CP2112"* ]]; then
			i2c_devpath=$(echo ${filename%/*})
			echo "ina219 0x41" > ${i2c_devpath}/new_device
			echo "ina219 0x44" > ${i2c_devpath}/new_device
			echo "ltc4151 0x69" > ${i2c_devpath}/new_device
			echo "ltc4151 0x6f" > ${i2c_devpath}/new_device
		fi
	done

	# for setup power monitor ina219 shunt resistor as 1 mohm
	for filename in /sys/class/hwmon/hwmon*/name; do
		hwmon_devname=$(cat ${filename})
		if [[ $hwmon_devname == *"ina219"* ]]; then
			hwmon_devpath=$(echo ${filename%/*})
			echo "1000" > ${hwmon_devpath}/shunt_resistor
		fi
	done
}

unbind_hwm_driver() {
	for filename in /sys/bus/i2c/devices/i2c-*/name; do
		i2c_devname=$(cat ${filename})
		if [[ $i2c_devname == *"CP2112"* ]]; then
			i2c_devpath=$(echo ${filename%/*})
			echo "0x41" > ${i2c_devpath}/delete_device
			echo "0x44" > ${i2c_devpath}/delete_device
			echo "0x69" > ${i2c_devpath}/delete_device
			echo "0x6f" > ${i2c_devpath}/delete_device
		fi
	done
}

initial_it87_uart() {
	# UART 1 GPIO init
	gpio_set_value "$(gp 14)" 0 # GP14 UR1_232EN
	gpio_set_value "$(gp 11)" 0 # GP11 UR1_485
	gpio_set_value "$(gp 12)" 0 # GP12 UR1_422

	# UART 2 GPIO init
	gpio_set_value "$(gp 30)" 0 # GP30 UR2_232EN
	gpio_set_value "$(gp 15)" 0 # GP15 UR2_485
	gpio_set_value "$(gp 16)" 0 # GP16 UR2_422

	# UART 3 GPIO init
	gpio_set_value "$(gp 36)" 0 # GP36 UR3_232EN
	gpio_set_value "$(gp 32)" 0 # GP32 UR3_485
	gpio_set_value "$(gp 33)" 0 # GP33 UR3_422

	# UART 4 GPIO init
	gpio_set_value "$(gp 50)" 0 # GP50 UR4_232EN
	gpio_set_value "$(gp 37)" 0 # GP37 UR4_485
	gpio_set_value "$(gp 47)" 0 # GP47 UR4_422

	# setup UART port0~3 default mode as RS-232
	/sbin/mx-uart-ctl -p 0 -m 0
	/sbin/mx-uart-ctl -p 1 -m 0
	/sbin/mx-uart-ctl -p 2 -m 0
	/sbin/mx-uart-ctl -p 3 -m 0
}

case "$1" in
	start)
		bind_hwm_driver
		get_gpio_it87_base
		initial_it87_uart
	;;
	stop)
		unbind_hwm_driver
	;;
	*)
		echo "Usage: $0 start|stop" >&2
		exit 3
	;;
esac
