#!/bin/bash

# HIGH means miniPCIe for cellular, LOW means for wifi
power_on_cellular_module() {
	for filename in /sys/class/gpio/dip_sel_*/value; do
		value=$(cat ${filename})
		if [[ $value == 1 ]]; then
			devpath=$(echo ${filename%/*})
			index=$(echo ${devpath##*dip_sel_})
                        echo 1 > /sys/class/gpio/pciepwr_${index}/value
		fi
	done
}

power_on_cellular_module
