#!/bin/bash

# HIGH means miniPCIe for cellular, LOW means for wifi do nothing
power_on_cellular_module() {
	# check dip slots and power on celluar
	if [[ $(cat /sys/class/gpio/gpio455/value) == 1 ]]; then
		mx-module-ctl -s 1 -p on
	fi
	
	# check dip slots and power on celluar
	if [[ $(cat /sys/class/gpio/gpio487/value) == 1 ]]; then
		mx-module-ctl -s 2 -p on
	fi
}

# restart hotswapd daemon due to LED is off
restart_hotswapd() {
	systemctl restart mx_hotswapd
}

power_on_cellular_module
restart_hotswapd
