#!/bin/bash
#
# SPDX-License-Identifier: Apache-2.0
#
# Authors:
#	2019	Elvis Yao <ElvisCW.Yao@moxa.com>
#
# Description:
#	For Moxa V-2406C series
#

init_gpio () {
	local gpio=${1}
	local direction=${2}
	local value=${3}
	if [ ! -e "/sys/class/gpio/gpio${gpio}" ]; then
		echo ${gpio} > "/sys/class/gpio/export"
	fi

	if [ "${direction}" == "out" ]; then
                echo ${direction} > "/sys/class/gpio/gpio${gpio}/direction"
                [ ! -z "${active_low}" ] && \
                        echo ${active_low} > "/sys/class/gpio/gpio${gpio}/active_low"
                [ ! -z "${value}" ] && \
                        echo ${value} > "/sys/class/gpio/gpio${gpio}/value"
	fi
}

bind_hwm_driver() {
	for filename in /sys/bus/i2c/devices/i2c-*/name; do
		i2c_devname=$(cat ${filename})
		if [[ $i2c_devname == *"CP2112"* ]]; then
			i2c_devpath=$(echo ${filename%/*})
			echo "ina219 0x41" > ${i2c_devpath}/new_device
			echo "ina219 0x44" > ${i2c_devpath}/new_device
			echo "ltc4151 0x69" > ${i2c_devpath}/new_device
			echo "ltc4151 0x6f" > ${i2c_devpath}/new_device
		fi
	done

	# for setup power monitor ina219 shunt resistor as 1 mohm
	for filename in /sys/class/hwmon/hwmon*/name; do
		hwmon_devname=$(cat ${filename})
		if [[ $hwmon_devname == *"ina219"* ]]; then
			hwmon_devpath=$(echo ${filename%/*})
			echo "1000" > ${hwmon_devpath}/shunt_resistor
		fi
	done
}

unbind_hwm_driver() {
	for filename in /sys/bus/i2c/devices/i2c-*/name; do
		i2c_devname=$(cat ${filename})
		if [[ $i2c_devname == *"CP2112"* ]]; then
			i2c_devpath=$(echo ${filename%/*})
			echo "0x41" > ${i2c_devpath}/delete_device
			echo "0x44" > ${i2c_devpath}/delete_device
			echo "0x69" > ${i2c_devpath}/delete_device
			echo "0x6f" > ${i2c_devpath}/delete_device
		fi
	done
}

# HIGH means miniPCIe for cellular, LOW means for wifi do nothing
power_on_cellular_module() {
	# check DIP slots is LTE mode and power on it
	if [[ $(cat /sys/class/gpio/gpio455/value) == 1 ]]; then
		mx-module-ctl -s 1 -p on
	fi

	# check dip slots and power on celluar
	if [[ $(cat /sys/class/gpio/gpio487/value) == 1 ]]; then
		mx-module-ctl -s 2 -p on
	fi
}

initial_it87_uart() {
	# Port 1
	init_gpio "444" "out" "1"
	init_gpio "441" "out" "0"
	init_gpio "442" "out" "0"

	# Port 2
	init_gpio "456" "out" "1"
	init_gpio "445" "out" "0"
	init_gpio "446" "out" "0"

	# Port 3
	init_gpio "462" "out" "1"
	init_gpio "458" "out" "0"
	init_gpio "459" "out" "0"

	# Port 4
	init_gpio "472" "out" "1"
	init_gpio "463" "out" "0"
	init_gpio "471" "out" "0"
}

initial_cellular() {
	# initial cellular PWR pins
	init_gpio "497" "out" "0"
	init_gpio "499" "out" "0"

	# set first sim card slot by default
	init_gpio "496" "out" "0"
	init_gpio "498" "out" "0"
}

initial_dio() {
	# setup DIO output pins (DO0~DO1)
	init_gpio "494" "out" "0"
	init_gpio "495" "out" "0"

	# export DIO input pins (DI0~DI5)
	init_gpio "488"
	init_gpio "489"
	init_gpio "490"
	init_gpio "491"
	init_gpio "492"
	init_gpio "493"
}

initial_dip_switch() {
	# export dip switch gpio pins
	init_gpio "455"
	init_gpio "487"
}

case "$1" in
	start)
		bind_hwm_driver
		initial_it87_uart
		initial_dio
		initial_cellular
		initial_dip_switch
		power_on_cellular_module
		systemctl restart moxa-module-control.service
	;;
	stop)
		unbind_hwm_driver
	;;
	*)
		echo "Usage: $0 start|stop" >&2
		exit 3
	;;
esac
